.TH ljar 1
.SH NAME
ljar \- Locking wrapper for jar.
.SH SYNOPSIS
.B ljar
[\fIOPTION\fR]... [\fIMAKEFILE\fR]...
.SH DESCRIPTION
.B ljar
calls jar with the supplied arguments, first locking a lock file, and replacing option \fIc\fR with \fIu\fR in case the archive already exists.
.SH SEE ALSO
.BR jar (1)
.SH AUTHOR
Written by Christian Hujer.
.SH REPORTING BUGS
Report bugs via <https://github.com/christianhujer/ljar/issues>
.SH COPYRIGHT
Copyright © 2015 Chrsitian Hujer.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
